package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateOverlay writes a docker-compose overlay YAML from the given service
// specs. The output is written atomically (temp file + rename).
func GenerateOverlay(services []*ServiceSpec, outputPath string) error {
	var b strings.Builder

	b.WriteString("# Auto-generated by curlycatclaw-updater. Do not edit.\n")

	if len(services) == 0 {
		b.WriteString("services: {}\n")
		return writeAtomic(outputPath, b.String())
	}

	// Collect all volume names across services for the top-level volumes section.
	volumeSet := make(map[string]struct{})

	b.WriteString("services:\n")

	for _, svc := range services {
		b.WriteString("  ")
		b.WriteString(svc.Name)
		b.WriteString(":\n")

		b.WriteString("    image: ")
		b.WriteString(svc.Image)
		b.WriteString("\n")

		if len(svc.Ports) > 0 {
			b.WriteString("    ports:\n")
			for _, host := range sortedKeys(svc.Ports) {
				container := svc.Ports[host]
				b.WriteString("      - \"")
				b.WriteString(host)
				b.WriteString(":")
				b.WriteString(container)
				b.WriteString("\"\n")
			}
		}

		if len(svc.Volumes) > 0 {
			b.WriteString("    volumes:\n")
			for _, volName := range sortedKeys(svc.Volumes) {
				containerPath := svc.Volumes[volName]
				b.WriteString("      - ")
				b.WriteString(volName)
				b.WriteString(":")
				b.WriteString(containerPath)
				b.WriteString("\n")
				volumeSet[volName] = struct{}{}
			}
		}

		if len(svc.Env) > 0 {
			b.WriteString("    environment:\n")
			for _, key := range sortedKeys(svc.Env) {
				b.WriteString("      ")
				b.WriteString(key)
				b.WriteString(": ")
				b.WriteString(yamlQuote(svc.Env[key]))
				b.WriteString("\n")
			}
		}

		if svc.Healthcheck != nil {
			b.WriteString("    healthcheck:\n")
			if len(svc.Healthcheck.Test) > 0 {
				b.WriteString("      test: [")
				for i, part := range svc.Healthcheck.Test {
					if i > 0 {
						b.WriteString(", ")
					}
					// Always quote healthcheck test elements and escape internal quotes
					// to prevent YAML injection.
					escaped := strings.ReplaceAll(part, `\`, `\\`)
					escaped = strings.ReplaceAll(escaped, `"`, `\"`)
					b.WriteString(`"`)
					b.WriteString(escaped)
					b.WriteString(`"`)
				}
				b.WriteString("]\n")
			}
			interval := svc.Healthcheck.Interval
			if interval == "" {
				interval = "10s"
			}
			b.WriteString("      interval: ")
			b.WriteString(interval)
			b.WriteString("\n")

			timeout := svc.Healthcheck.Timeout
			if timeout == "" {
				timeout = "5s"
			}
			b.WriteString("      timeout: ")
			b.WriteString(timeout)
			b.WriteString("\n")

			retries := svc.Healthcheck.Retries
			if retries == 0 {
				retries = 3
			}
			fmt.Fprintf(&b, "      retries: %d\n", retries)
		}

		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    networks:\n")
		b.WriteString("      - default\n")
	}

	if len(volumeSet) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, name := range sortedSetKeys(volumeSet) {
			b.WriteString("  ")
			b.WriteString(name)
			b.WriteString(":\n")
		}
	}

	return writeAtomic(outputPath, b.String())
}

// writeAtomic writes content to a temp file and renames it into place.
func writeAtomic(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("compose_gen: create dir: %w", err)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return fmt.Errorf("compose_gen: write tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp) //nolint:errcheck
		return fmt.Errorf("compose_gen: rename: %w", err)
	}
	return nil
}

// sortedKeys returns the keys of a string map in sorted order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// sortedSetKeys returns the keys of a set-style map in sorted order.
func sortedSetKeys(m map[string]struct{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// yamlQuote wraps a value in double quotes if it contains characters that
// need quoting in YAML, or returns it bare for simple values.
func yamlQuote(s string) string {
	if s == "" {
		return `""`
	}
	// Quote if the value contains special YAML characters or looks like
	// a non-string type (bool, number, null).
	needsQuote := false
	for _, c := range s {
		if c == ':' || c == '#' || c == '{' || c == '}' || c == '[' || c == ']' ||
			c == ',' || c == '&' || c == '*' || c == '?' || c == '|' || c == '-' ||
			c == '<' || c == '>' || c == '=' || c == '!' || c == '%' || c == '@' ||
			c == '`' || c == '"' || c == '\'' || c == ' ' || c == '\t' || c == '\n' {
			needsQuote = true
			break
		}
	}
	// Also quote values that look like booleans or null.
	lower := strings.ToLower(s)
	if lower == "true" || lower == "false" || lower == "null" || lower == "yes" || lower == "no" {
		needsQuote = true
	}
	if needsQuote {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}
