package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateOverlayEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	if err := GenerateOverlay(nil, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Auto-generated by curlycatclaw-updater") {
		t.Error("missing header comment")
	}
	if !strings.Contains(content, "services: {}") {
		t.Errorf("expected empty services block, got:\n%s", content)
	}
}

func TestGenerateOverlaySingleService(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	services := []*ServiceSpec{
		{
			Name:  "redis",
			Image: "redis:7-alpine",
			Ports: map[string]string{"6379": "6379"},
			Volumes: map[string]string{
				"redis-data": "/data",
			},
			Env: map[string]string{
				"REDIS_ARGS": "--maxmemory 256mb",
			},
			Healthcheck: &Healthcheck{
				Test:     []string{"CMD", "redis-cli", "ping"},
				Interval: "15s",
				Timeout:  "3s",
				Retries:  5,
			},
			AddedAt: time.Now(),
		},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)

	// Verify header.
	if !strings.Contains(content, "Auto-generated by curlycatclaw-updater") {
		t.Error("missing header comment")
	}

	// Verify service block.
	if !strings.Contains(content, "  redis:") {
		t.Error("missing service name")
	}
	if !strings.Contains(content, "    image: redis:7-alpine") {
		t.Error("missing image line")
	}

	// Verify ports.
	if !strings.Contains(content, `      - "6379:6379"`) {
		t.Error("missing port mapping")
	}

	// Verify volumes.
	if !strings.Contains(content, "      - redis-data:/data") {
		t.Error("missing volume mapping")
	}

	// Verify environment (value with spaces should be quoted).
	if !strings.Contains(content, `      REDIS_ARGS: "--maxmemory 256mb"`) {
		t.Errorf("missing or incorrect environment line, got:\n%s", content)
	}

	// Verify healthcheck.
	if !strings.Contains(content, `      test: ["CMD", "redis-cli", "ping"]`) {
		t.Error("missing healthcheck test")
	}
	if !strings.Contains(content, "      interval: 15s") {
		t.Error("missing healthcheck interval")
	}
	if !strings.Contains(content, "      timeout: 3s") {
		t.Error("missing healthcheck timeout")
	}
	if !strings.Contains(content, "      retries: 5") {
		t.Error("missing healthcheck retries")
	}

	// Verify restart and networks.
	if !strings.Contains(content, "    restart: unless-stopped") {
		t.Error("missing restart policy")
	}
	if !strings.Contains(content, "      - default") {
		t.Error("missing default network")
	}

	// Verify top-level volumes.
	if !strings.Contains(content, "\nvolumes:\n  redis-data:\n") {
		t.Errorf("missing top-level volumes section, got:\n%s", content)
	}
}

func TestGenerateOverlayMultipleServices(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	now := time.Now()
	services := []*ServiceSpec{
		{
			Name:    "redis",
			Image:   "redis:7",
			AddedAt: now,
		},
		{
			Name:    "postgres",
			Image:   "postgres:16",
			Env:     map[string]string{"POSTGRES_PASSWORD": "secret"},
			AddedAt: now.Add(time.Second),
		},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)

	if !strings.Contains(content, "  redis:") {
		t.Error("missing redis service")
	}
	if !strings.Contains(content, "  postgres:") {
		t.Error("missing postgres service")
	}
	if !strings.Contains(content, "    image: redis:7") {
		t.Error("missing redis image")
	}
	if !strings.Contains(content, "    image: postgres:16") {
		t.Error("missing postgres image")
	}
}

func TestGenerateOverlayVolumeDedup(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	now := time.Now()
	services := []*ServiceSpec{
		{
			Name:    "svc-a",
			Image:   "img:1",
			Volumes: map[string]string{"shared-vol": "/data/a"},
			AddedAt: now,
		},
		{
			Name:    "svc-b",
			Image:   "img:2",
			Volumes: map[string]string{"shared-vol": "/data/b", "extra-vol": "/extra"},
			AddedAt: now.Add(time.Second),
		},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)

	// Count occurrences of "shared-vol:" in the top-level volumes section.
	// The volumes section should have exactly one entry for shared-vol.
	volumeSection := content[strings.LastIndex(content, "\nvolumes:\n"):]
	sharedCount := strings.Count(volumeSection, "shared-vol:")
	if sharedCount != 1 {
		t.Errorf("shared-vol appears %d times in volumes section, want 1; section:\n%s", sharedCount, volumeSection)
	}

	// extra-vol should also appear exactly once.
	extraCount := strings.Count(volumeSection, "extra-vol:")
	if extraCount != 1 {
		t.Errorf("extra-vol appears %d times in volumes section, want 1", extraCount)
	}
}

func TestGenerateOverlayHealthcheckDefaults(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	services := []*ServiceSpec{
		{
			Name:  "svc",
			Image: "img:1",
			Healthcheck: &Healthcheck{
				Test: []string{"CMD-SHELL", "curl -f http://localhost/health"},
				// Interval, Timeout, Retries all zero/empty -> defaults.
			},
			AddedAt: time.Now(),
		},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)

	if !strings.Contains(content, "      interval: 10s") {
		t.Error("missing default interval")
	}
	if !strings.Contains(content, "      timeout: 5s") {
		t.Error("missing default timeout")
	}
	if !strings.Contains(content, "      retries: 3") {
		t.Error("missing default retries")
	}
}

func TestGenerateOverlayNoVolumesSection(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overlay.yml")

	services := []*ServiceSpec{
		{
			Name:    "svc",
			Image:   "img:1",
			AddedAt: time.Now(),
		},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)
	if strings.Contains(content, "volumes:") {
		t.Errorf("should not have top-level volumes section when no volumes, got:\n%s", content)
	}
}

// TestYamlQuote_EscapesBackslashes is a regression test for a bug where
// env values containing backslashes that ALSO triggered quoting (e.g. a
// value with a space AND a backslash) were emitted with the backslash
// unescaped. YAML-in-double-quotes interprets `\n` as a newline, so
// `"foo \nbar"` would parse as "foo <newline>bar", corrupting the value.
func TestYamlQuote_EscapesBackslashes(t *testing.T) {
	// The space triggers quoting. The backslash must be doubled so YAML
	// emits the literal `\n` (2 chars), not a newline.
	got := yamlQuote(`foo \nbar`)
	want := `"foo \\nbar"`
	if got != want {
		t.Errorf("yamlQuote(`foo \\nbar`) = %q, want %q", got, want)
	}
}

// TestYamlQuote_EscapesQuotesAfterBackslashes verifies escape ordering:
// backslash → \\ MUST happen before " → \", otherwise our own quote-escape
// collides with the value's backslash.
func TestYamlQuote_EscapesQuotesAfterBackslashes(t *testing.T) {
	got := yamlQuote(`a\"b`)
	want := `"a\\\"b"`
	if got != want {
		t.Errorf(`yamlQuote(a\"b) = %q, want %q`, got, want)
	}
}

func TestGenerateOverlayAtomicWrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sub", "deep", "overlay.yml")

	services := []*ServiceSpec{
		{Name: "svc", Image: "img:1", AddedAt: time.Now()},
	}

	if err := GenerateOverlay(services, path); err != nil {
		t.Fatalf("GenerateOverlay: %v", err)
	}

	// Verify file exists and no .tmp residue.
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("output file not created: %v", err)
	}
	if _, err := os.Stat(path + ".tmp"); err == nil {
		t.Error("temp file was not cleaned up")
	}
}
